name: docs
channels:
  - conda-forge
  - psi4
  - defaults
dependencies:
    # Base depends
  # - psi4
  - python
  - pip
  - sphinx
  # - numpy
  # - scipy
  - sphinx_automodapi


    # Testing
  - pytest
  - pytest-cov
  - codecov

    # Pip-only installs
  - pip:
    # - insegel
    - opt-einsum
