name: docs
channels:
  - conda-forge
  # - psi4
  - defaults
dependencies:
    # Base depends
  - python
  - pip
  - numpy
  - scipy
  # - psi4
  - pytest
  - pytest-cov
  - codecov


    # Pip-only installs
  - pip:
    - sphinx_automodapi
    - recommonmark
    - opt-einsum