name: docs
channels:
  - conda-forge
  - psi4
  - defaults
dependencies:
    # Base depends
  - python
  - pip
  - numpy
  - scipy
  - psi4
  - pytest
  - pytest-cov
  - codecov
  - sphinx_automodapi


    # Pip-only installs
  - pip:
    # - insegel

  - recommonmark
  # - readthedocs-sphinx-ext
  - opt-einsum